[build]
  command = "php build.php"
  publish = "dist"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  condition = {path = ["!/assets/*", "!/css/*", "!/js/*", "!/*.html", "!/sitemap.xml"]}
